// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfrobccwutycupmejobw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcm9iY2N3dXR5Y3VwbWVqb2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjgwMDUsImV4cCI6MjA2Mzc0NDAwNX0.oaK_en6UAa7EPYhNpvhCIGQbAS4h_eqvS7eZTduPD_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);